openapi: "3.0.0"
info:
  version: 1.0.0
  title: DID Actor API
  description: Identifier and Credentials APIs for DID.
  license:
    name: Apache.20
  contact:
    name: API Support
    url: https://github.com/transmute-industries/api.did.actor
servers:
  - url: https://vc.mesur.io
  - url: https://api.did.actor
  - url: http://localhost:3000

tags:
  - name: Discovery
  - name: Identifiers
  - name: Credentials
  - name: Presentations
  - name: Ciphers
paths:
  /did.json:
    $ref: "./resources/traceability-api-did-web.yml"
  /identifiers/{did}:
    $ref: "./resources/did.yml"

  /api/credentials/issue:
    $ref: "./resources/credential-issuer.yml"
  /api/credentials/verify:
    $ref: "./resources/credential-verifier.yml"
  /credentials/{credential-id}:
    $ref: "./resources/credential.yml"

  /api/presentations/prove:
    $ref: "./resources/presentation-prover.yml"
  /api/presentations/verify:
    $ref: "./resources/presentation-verifier.yml"
  /api/presentations/available:
    $ref: "./resources/presentation-available.yml"
  /api/presentations/submissions:
    $ref: "./resources/presentation-submissions.yml"

  /api/ciphers/encrypt:
    $ref: "./resources/cipher-encrypt.yml"
  /api/ciphers/decrypt:
    $ref: "./resources/cipher-decrypt.yml"
components:
  parameters:
    $ref: "./parameters/_index.yml"
  schemas:
    $ref: "./schemas/_index.yml"
  responses:
    $ref: "./responses/_index.yml"
